context('Disabling aliases ', function()
	local _ = require 'allen'
	test('Not defining ALLEN_ALIASES before calling Allen will not import aliases', function()
		assert_nil(_.capFirst)
		assert_nil(_.capEach)
		assert_nil(_.caps)
		assert_nil(_.cap)
		assert_nil(_.isLower)
		assert_nil(_.isUpper)
		assert_nil(_.startsLower)
		assert_nil(_.startsUpper)
		assert_nil(_.split)
		assert_nil(_.trim)
		assert_nil(_.esc)
		assert_nil(_.subst)
		assert_nil(_.interpolate)
		assert_nil(_.isNum)
		assert_nil(_.charAt)
		assert_nil(_.next)
		assert_nil(_.numFmt)
		assert_nil(_.rjust)
		assert_nil(_.ljust)
		assert_nil(_.center)
		assert_nil(_.isLuaKword)
		assert_nil(_.isReserved)
		assert_nil(_.isOperator)
		assert_nil(_.isOp)
		assert_nil(_.isIden)
		assert_nil(_.isVarName)
		assert_nil(_.stats)
	end)
	
end)

context('Enabling aliases', function()
	package.loaded.allen = nil
	_G.ALLEN_ALIASES = true
	local _ = require 'allen'
	
	test('Setting ALLEN_ALIASES to true before calling Allen will import aliases', function()
		assert_not_nil(_.capFirst)
		assert_not_nil(_.capEach)
		assert_not_nil(_.caps)
		assert_not_nil(_.cap)
		assert_not_nil(_.isLower)
		assert_not_nil(_.isUpper)
		assert_not_nil(_.startsLower)
		assert_not_nil(_.startsUpper)
		assert_not_nil(_.split)
		assert_not_nil(_.trim)
		assert_not_nil(_.esc)
		assert_not_nil(_.subst)
		assert_not_nil(_.interpolate)
		assert_not_nil(_.isNum)
		assert_not_nil(_.charAt)
		assert_not_nil(_.next)
		assert_not_nil(_.numFmt)
		assert_not_nil(_.rjust)
		assert_not_nil(_.ljust)
		assert_not_nil(_.center)
		assert_not_nil(_.isLuaKword)
		assert_not_nil(_.isReserved)
		assert_not_nil(_.isOperator)
		assert_not_nil(_.isOp)
		assert_not_nil(_.isIden)
		assert_not_nil(_.isVarName)
		assert_not_nil(_.stats)
	end)
	
end)